import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1560, height: 940 } })
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'networkidle' })
await page.waitForTimeout(2500)
await page.locator('nav[aria-label="收件箱"] button').nth(6).click()
await page.waitForTimeout(3500)
await page.locator('button', { hasText: '轻问' }).first().click()
await page.waitForTimeout(400)
await page.locator('textarea').first().fill('这个群里对外发数字有什么规矩？一句话回答。')
await page.locator('button', { hasText: '轻问' }).last().click()
console.log('sent, waiting…')
await page.waitForTimeout(70000)
await page.screenshot({ path: '.acceptance/m0/v5-ask.png' })
const rows = await page.locator('[class*="column_msg"]').allInnerTexts()
console.log(rows.slice(-4).map(r => r.replace(/\s+/g, ' ').slice(0, 200)).join('\n---\n'))
await browser.close()
