import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1560, height: 940 } })
const errors = []
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'networkidle' })
await page.waitForTimeout(3000)
// open the newest topic (the one that just answered)
await page.locator('nav[aria-label="收件箱"] button').filter({ hasText: '用一句话说明' }).first().click()
await page.waitForTimeout(4000)
await page.locator('button', { hasText: '轻问' }).first().click()
await page.waitForTimeout(400)
await page.locator('textarea').first().fill('我在这个群里一共开过几个话题？只回一个数字和它的出处。')
await page.locator('button', { hasText: '轻问' }).last().click()
console.log('ask sent…')
await page.waitForTimeout(80000)
await page.screenshot({ path: '.acceptance/m0/v8-ask.png' })
const rows = await page.locator('[class*="column_msg"]').allInnerTexts()
console.log(rows.slice(-3).map(r => r.replace(/\s+/g, ' ').slice(0, 260)).join('\n---\n'))
console.log('console errors:', errors.length ? errors.slice(0,2) : 'none')
await browser.close()
