import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1560, height: 940 } })
const errors = []
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'networkidle' })
await page.waitForTimeout(3000)
await page.locator('button[title*="打开一个本地工作目录"]').first().click()
await page.waitForTimeout(2500)
await page.screenshot({ path: '.acceptance/m0/v11-picker.png' })
const dirs = await page.locator('[class*="picker_entryName"]').allInnerTexts()
console.log('directories listed:', dirs.length, dirs.slice(0, 6))
console.log('current path:', await page.locator('[class*="picker_current"]').innerText().catch(() => 'n/a'))
console.log('errors:', errors.length ? errors.slice(0,2) : 'none')
await browser.close()
