import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1560, height: 940 } })
const errors = []
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
page.on('response', async r => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()) })
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'networkidle' })
await page.waitForTimeout(3000)
await page.locator('nav[aria-label="收件箱"] button[title*="群视图"]').first().click()
await page.waitForTimeout(6000)
await page.screenshot({ path: '.acceptance/m0/v9-place.png' })
const names = await page.locator('[class*="place_name"]').allInnerTexts()
console.log('speakers rendered:', JSON.stringify([...new Set(names)]))
const stale = await page.locator('[class*="place_stale"]').allInnerTexts()
console.log('stale:', stale.join(' | ') || 'none')
console.log('errors:', errors.length ? errors.slice(0,3) : 'none')
await browser.close()
