import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1560, height: 940 } })
const errors = []
page.on('pageerror', e => errors.push('pageerror: ' + e.message))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'networkidle' })
await page.waitForTimeout(4000)
// open a local session so it becomes "current"
const locals = page.locator('nav[aria-label="收件箱"] button').filter({ hasText: '本地会话' })
console.log('local session rows:', await locals.count())
await locals.first().click()
await page.waitForTimeout(2500)
const beforeText = await page.locator('nav[aria-label="收件箱"]').innerText()
// collapse the folder that holds it (云之家)
const chevs = page.getByRole('button', { name: '折叠' })
const n = await chevs.count()
await chevs.nth(n - 1).click()
await page.waitForTimeout(1000)
const afterText = await page.locator('nav[aria-label="收件箱"]').innerText()
console.log('current row still visible after collapse:', afterText.includes('本地会话'))
console.log('sibling rows hidden:', (beforeText.match(/本地会话/g) || []).length, '->', (afterText.match(/本地会话/g) || []).length)
await page.screenshot({ path: '.acceptance/m0/v18-collapsed-current.png' })
console.log('errors:', errors.length ? errors : 'none')
await browser.close()
